### ISSUE TITLE
SSR (no window or storage)

### ISSUE THREAD

**Issue by wKovacs64** [soyguijarro/react-storage-hooks#1]
This currently can't be used in a server-side rendered app because `localStorage`, `sessionStorage`, and `window` don't exist.

```js
ReferenceError: localStorage is not defined
```

Can we add either some mock objects or noops if these are missing?

Thanks!

**Comment by soyguijarro** [comment]
Hi, thanks for reporting! Can't look into this right now, will try to do it in a couple of weeks.

**Comment by soyguijarro** [comment]
@wKovacs64 Fixed in version 3.0.0 (already released). I haven't actually tried it in a SSR project but it should work, I added specific tests for this with the environment set to Node.
