### ISSUE TITLE
Clearing of keys in storages is absent

### ISSUE THREAD

**Issue by adrianplavka** [soyguijarro/react-storage-hooks#10]
Hello,

thanks for providing this hook, works good when I tested it for my use-case.

Although while working with it, there is one operation that is missing for me - clearing of the keys in various storages. I am aware, that I could just set the value of the key to an empty one (e.g. setting it to an empty string), but when I'm done with the key, I would expect to remove it altogether from these storages, as to not clutter the storage with empty keys.

Thanks in advance!

**Comment by soyguijarro** [comment]
Hi @adrianplavka, thanks for bringing this up!

I'm working on a full rewrite of the library, so I'll tackle this feature as part of that. Right now I'm thinking about removing the key when the `setState` function is called with `null` or `undefined`. That way the hook wouldn't need to return an extra function for removal or anything. I think there's value in keeping the API as close as possible to the built-in hooks.

Would that work for you?

**Comment by adrianplavka** [comment]
I like the idea, adding an extra function for this would certainly make it more "heavy".

I'm thinking about the approach you provided and one thing comes to mind - if user called `setState` with `undefined`, I would expect that the state would be set to `undefined` & if it was called with `null`, the state should be also set to `null`, as to prevent any bugs that could come up with equality comparisons.

This means, that you'd also have to remember the values in the hook itself. I don't know, how you're approaching this problem currently, as I didn't dig into your source code, but hopefully it won't be a problem.

**Comment by soyguijarro** [comment]
Great, thanks for your input!

**Comment by soyguijarro** [comment]
@adrianplavka I've just published version 4.0.0 on npm which includes this feature (calling `setState` with `null`). So closing this. Thanks!
