### ISSUE TITLE
React Native window.addEventListener is not a function

### ISSUE THREAD

**Issue by jgornick** [soyguijarro/react-storage-hooks#15]
<img width="200" alt="Android Emulator - rnw-starter-native-emulator:5554 2020-06-05 19-43-41" src="https://user-images.githubusercontent.com/8788/83931972-45096300-a765-11ea-8ea2-c8e65c494628.png">

Looks like a check for not just `window` is required, but `window.addEventListener`. 

PR coming...

**Comment by soyguijarro** [comment]
Fixed by https://github.com/soyguijarro/react-storage-hooks/pull/16
