### ISSUE TITLE
Cannot import in non-TS projects

### ISSUE THREAD

**Issue by Dema** [soyguijarro/react-storage-hooks#2]
```
node_modules/react-storage-hooks/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { import { useState, useReducer } from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import```

Looks like the code is compiled for es6+, Could you recompile it using es5 as a target.

**Comment by soyguijarro** [comment]
Thanks for reporting, @Dema! I'll try to fix this next week, I want to take a look at [@pika/pack](https://github.com/pikapkg/pack) to distribute a package optimized for different targets.

**Comment by soyguijarro** [comment]
@Dema I changed the compilation target to es5 for now, this should fix the issue. Please try version 3.0.1.

I've created #3 to investigate more complete solutions when I have some time.
